//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxDome.AvaloniaApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaxDome.AvaloniaApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxDome.
        /// </summary>
        internal static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied Actions.
        /// </summary>
        internal static string DocumentHistory_Column_AppliedActions {
            get {
                return ResourceManager.GetString("DocumentHistory_Column_AppliedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Actions.
        /// </summary>
        internal static string DocumentHistory_Column_AvailableActions {
            get {
                return ResourceManager.GetString("DocumentHistory_Column_AvailableActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client &amp; Folder.
        /// </summary>
        internal static string DocumentHistory_Column_ClientAndFolder {
            get {
                return ResourceManager.GetString("DocumentHistory_Column_ClientAndFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string DocumentHistory_Column_Document {
            get {
                return ResourceManager.GetString("DocumentHistory_Column_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string DocumentHistory_Search {
            get {
                return ResourceManager.GetString("DocumentHistory_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Documents.
        /// </summary>
        internal static string DocumentHistory_SelectDocuments {
            get {
                return ResourceManager.GetString("DocumentHistory_SelectDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document History.
        /// </summary>
        internal static string DocumentHistory_Title {
            get {
                return ResourceManager.GetString("DocumentHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        internal static string DocumentHistory_UploadFiles {
            get {
                return ResourceManager.GetString("DocumentHistory_UploadFiles", resourceCulture);
            }
        }
    }
}
