//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxDome.AvaloniaApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaxDome.AvaloniaApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxDome.
        /// </summary>
        internal static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Applied Actions.
        /// </summary>
        internal static string DocumentHistory_AllAppliedActions {
            get {
                return ResourceManager.GetString("DocumentHistory_AllAppliedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Clients.
        /// </summary>
        internal static string DocumentHistory_AllClients {
            get {
                return ResourceManager.GetString("DocumentHistory_AllClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Folders.
        /// </summary>
        internal static string DocumentHistory_AllFolders {
            get {
                return ResourceManager.GetString("DocumentHistory_AllFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied Actions.
        /// </summary>
        internal static string DocumentHistory_Column_AppliedActions {
            get {
                return ResourceManager.GetString("DocumentHistory_Column_AppliedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Actions.
        /// </summary>
        internal static string DocumentHistory_Column_AvailableActions {
            get {
                return ResourceManager.GetString("DocumentHistory_Column_AvailableActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client &amp; Folder.
        /// </summary>
        internal static string DocumentHistory_Column_ClientAndFolder {
            get {
                return ResourceManager.GetString("DocumentHistory_Column_ClientAndFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string DocumentHistory_Column_Document {
            get {
                return ResourceManager.GetString("DocumentHistory_Column_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Selection.
        /// </summary>
        internal static string DocumentHistory_HideSelectionDocuments {
            get {
                return ResourceManager.GetString("DocumentHistory_HideSelectionDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string DocumentHistory_Search {
            get {
                return ResourceManager.GetString("DocumentHistory_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by file name, client name....
        /// </summary>
        internal static string DocumentHistory_SearchTextWatermark {
            get {
                return ResourceManager.GetString("DocumentHistory_SearchTextWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Documents.
        /// </summary>
        internal static string DocumentHistory_SelectDocuments {
            get {
                return ResourceManager.GetString("DocumentHistory_SelectDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document History.
        /// </summary>
        internal static string DocumentHistory_Title {
            get {
                return ResourceManager.GetString("DocumentHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        internal static string DocumentHistory_UploadFiles {
            get {
                return ResourceManager.GetString("DocumentHistory_UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string UploadFiles_Cancel {
            get {
                return ResourceManager.GetString("UploadFiles_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Files.
        /// </summary>
        internal static string UploadFiles_ChooseFiles {
            get {
                return ResourceManager.GetString("UploadFiles_ChooseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client:.
        /// </summary>
        internal static string UploadFiles_Client {
            get {
                return ResourceManager.GetString("UploadFiles_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a client to enable folder selection for files.
        /// </summary>
        internal static string UploadFiles_ClientHint {
            get {
                return ResourceManager.GetString("UploadFiles_ClientHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search and select client....
        /// </summary>
        internal static string UploadFiles_ClientWatermark {
            get {
                return ResourceManager.GetString("UploadFiles_ClientWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop files or choose manually.
        /// </summary>
        internal static string UploadFiles_DragAndDropFiles {
            get {
                return ResourceManager.GetString("UploadFiles_DragAndDropFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Files.
        /// </summary>
        internal static string UploadFiles_OpenFiles {
            get {
                return ResourceManager.GetString("UploadFiles_OpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string UploadFiles_Preview {
            get {
                return ResourceManager.GetString("UploadFiles_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Files ({0}).
        /// </summary>
        internal static string UploadFiles_SelectedFiles {
            get {
                return ResourceManager.GetString("UploadFiles_SelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Select a client to proceed.
        /// </summary>
        internal static string UploadFiles_Step1 {
            get {
                return ResourceManager.GetString("UploadFiles_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Configure files and folders.
        /// </summary>
        internal static string UploadFiles_Step2 {
            get {
                return ResourceManager.GetString("UploadFiles_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Review.
        /// </summary>
        internal static string UploadFiles_Title {
            get {
                return ResourceManager.GetString("UploadFiles_Title", resourceCulture);
            }
        }
    }
}
