//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxDome.AvaloniaApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaxDome.AvaloniaApp.Resources.Strings.ru", typeof(Strings_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxDome.
        /// </summary>
        internal static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все примененные действия.
        /// </summary>
        internal static string DocumentHistory_AllAppliedActions {
            get {
                return ResourceManager.GetString("DocumentHistory_AllAppliedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все клиенты.
        /// </summary>
        internal static string DocumentHistory_AllClients {
            get {
                return ResourceManager.GetString("DocumentHistory_AllClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все папки.
        /// </summary>
        internal static string DocumentHistory_AllFolders {
            get {
                return ResourceManager.GetString("DocumentHistory_AllFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примененные действия.
        /// </summary>
        internal static string DocumentHistory_Column_AppliedActions {
            get {
                return ResourceManager.GetString("DocumentHistory_Column_AppliedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступные действия.
        /// </summary>
        internal static string DocumentHistory_Column_AvailableActions {
            get {
                return ResourceManager.GetString("DocumentHistory_Column_AvailableActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент и папка.
        /// </summary>
        internal static string DocumentHistory_Column_ClientAndFolder {
            get {
                return ResourceManager.GetString("DocumentHistory_Column_ClientAndFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ.
        /// </summary>
        internal static string DocumentHistory_Column_Document {
            get {
                return ResourceManager.GetString("DocumentHistory_Column_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть выделение.
        /// </summary>
        internal static string DocumentHistory_HideSelectionDocuments {
            get {
                return ResourceManager.GetString("DocumentHistory_HideSelectionDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск:.
        /// </summary>
        internal static string DocumentHistory_Search {
            get {
                return ResourceManager.GetString("DocumentHistory_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по имени файла, клиенту....
        /// </summary>
        internal static string DocumentHistory_SearchTextWatermark {
            get {
                return ResourceManager.GetString("DocumentHistory_SearchTextWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выделить документы.
        /// </summary>
        internal static string DocumentHistory_SelectDocuments {
            get {
                return ResourceManager.GetString("DocumentHistory_SelectDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История документов.
        /// </summary>
        internal static string DocumentHistory_Title {
            get {
                return ResourceManager.GetString("DocumentHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить файлы.
        /// </summary>
        internal static string DocumentHistory_UploadFiles {
            get {
                return ResourceManager.GetString("DocumentHistory_UploadFiles", resourceCulture);
            }
        }
    }
}
